# Generated by Django 4.0 on 2021-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('O`zbek', 'O`zbek'), ('O`zbek', 'O`zbek')], default='O`zbek', max_length=50),
            preserve_default=False,
        ),
    ]
