# Generated by Django 4.0 on 2021-11-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('O`zbek', 'O`zbek'), ('Rus', 'Rus')], max_length=50),
        ),
    ]
