# Generated by Django 4.0 on 2021-12-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.CharField(default='13', max_length=7),
            preserve_default=False,
        ),
    ]
