# Generated by Django 4.0 on 2021-12-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
    ]
