# Generated by Django 4.0 on 2021-12-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_button',
            field=models.CharField(choices=[('soat', 'soat'), ('daqiqa', 'daqiqa')], max_length=15),
        ),
    ]
