# Generated by Django 4.0 on 2021-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_time_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
