# Generated by Django 4.0 on 2021-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guaranted',
            field=models.CharField(blank=True, choices=[('30 kun kafolat', '30 kun kafolat')], max_length=200),
        ),
    ]
